/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-Just_For_Paws-lyGHXfZ1M-N2yH4Nx58PizOzsn98c5-g",
  "version": "2020-11-20"
}

export default ebconfig;